# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Example' do

pod "Appirater"  #评分 https://github.com/arashpayan/appirater
pod 'UMengAnalytics-NO-IDFA' #友盟 http://dev.umeng.com/analytics/ios-doc/integration
pod 'iVersion' #版本记录，提示有没有新版本 https://github.com/nicklockwood/iVersion

#pod 'MYBlurIntroductionView' #开始时的App功能介绍 https://github.com/MatthewYork/MYBlurIntroductionView
#pod 'ChameleonFramework/Swift' #扁平化的一些色彩和效果
#pod 'pop', '~> 1.0' # Facebook 提供的动画类 pop https://github.com/facebook/pop
#pod 'SwiftDate' #对日期操作的一些拓展 https://github.com/malcommac/SwiftDate
#pod 'AMPopTip', '~> 0.7' #https://github.com/andreamazz/AMPopTip

end

